import {
  SchoolConfig,
  AdmissionApplication,
  StudentResult,
  GalleryPhoto,
  NewsItem,
  ResultPin,
  Teacher,
} from '../types/school';

export const DEFAULT_SCHOOL_CONFIG: SchoolConfig = {
  name: 'Apex Royal Academy',
  motto: 'Knowledge, Integrity & Excellence',
  logoUrl: '', // Fallback crest will be rendered if empty, or can be a data URI
  address: 'Plot 14, Kings Avenue, Victoria Garden Estate, Lekki, Lagos State, Nigeria',
  phone: '+234 803 123 4567',
  altPhone: '+234 812 987 6543',
  whatsapp: '2348031234567',
  email: 'admissions@apexroyalacademy.edu.ng',
  primaryColor: '#1e3a8a', // Deep Royal Blue
  secondaryColor: '#f59e0b', // Radiant Gold / Amber
  accentColor: '#0284c7', // Sky Blue
  aboutTitle: 'Nurturing Global Leaders with Strong Moral & Academic Foundations',
  aboutHistory:
    'Founded in September 2008, Apex Royal Academy began with a steadfast vision to deliver world-class, holistic basic and secondary education. Over the past 17 years, we have grown into one of the nation’s premier day and boarding institutions, combining the rigorous Nigerian National Curriculum with the British Cambridge Assessment standards. Our students consistently secure outstanding grades in WAEC, NECO, IGCSE, and UTME examinations, progressing to leading universities worldwide.',
  mission:
    'To foster intellectual curiosity, moral fortitude, technological prowess, and leadership excellence in every student within a secure and nurturing environment.',
  vision:
    'To be the benchmark for academic distinction and character development in Africa, raising future-ready innovators and principled change-makers.',
  coreValues: [
    'Academic Rigour',
    'Moral Integrity',
    'Creative Innovation',
    'Global Mindset',
    'Discipline & Empathy',
  ],
  admissionNotice:
    'Admissions for the 2026/2027 Academic Session are currently open for Creche, Nursery, Primary, JSS 1-3, and SSS 1-2. Apply early to secure a slot for the upcoming entrance examination.',
  admissionIsOpen: true,
  academicSession: '2025/2026',
  currentTerm: '2nd Term',
  applicationFee: 5000,
  currencySymbol: '₦',
  designerName: 'EduPro Tech Solutions',
  designerUrl: 'https://wa.me/2348000000000',
  googleMapsEmbedUrl:
    'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d126839.81667080646!2d3.4116!3d6.4531!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x103bf4ccdd4d4db3%3A0xa61fc378d3807217!2sVictoria%20Island%2C%20Lagos!5e0!3m2!1sen!2sng!4v1689000000000!5m2!1sen!2sng',
  facebookUrl: 'https://facebook.com',
  instagramUrl: 'https://instagram.com',
  twitterUrl: 'https://twitter.com',
  youtubeUrl: 'https://youtube.com',
};

export const DEFAULT_APPLICATIONS: AdmissionApplication[] = [
  {
    id: 'app-001',
    applicationNumber: 'SCH/2026/0001',
    studentFullName: 'Chinedu Emmanuel Okonkwo',
    dateOfBirth: '2012-05-14',
    gender: 'Male',
    classApplyingFor: 'JSS 1',
    religion: 'Christianity',
    stateOfOrigin: 'Anambra State',
    lga: 'Aguata',
    parentFullName: 'Dr. & Mrs. Gabriel Okonkwo',
    parentPhone: '08023456789',
    parentEmail: 'g.okonkwo@gmail.com',
    parentOccupation: 'Consultant Surgeon',
    residentialAddress: '18 Admiralty Way, Lekki Phase 1, Lagos',
    previousSchool: 'Crown Heights Montessori School',
    lastClassPassed: 'Primary 5 / Year 5',
    passportPhoto: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=300&auto=format&fit=crop&q=80',
    submittedAt: '2026-03-02T10:15:00Z',
    status: 'Admitted',
    examDate: '2026-03-25',
    notes: 'Exceptional performance in mathematics screening test.',
  },
  {
    id: 'app-002',
    applicationNumber: 'SCH/2026/0002',
    studentFullName: 'Amina Fatima Bello',
    dateOfBirth: '2011-09-20',
    gender: 'Female',
    classApplyingFor: 'SSS 1 (Science)',
    religion: 'Islam',
    stateOfOrigin: 'Kaduna State',
    lga: 'Zaria',
    parentFullName: 'Alhaji Mansur Bello',
    parentPhone: '08134567890',
    parentEmail: 'mansur.bello@yahoo.com',
    parentOccupation: 'Civil Engineer',
    residentialAddress: '5 Bourdillon Road, Ikoyi, Lagos',
    previousSchool: 'Capital Science Academy, Abuja',
    lastClassPassed: 'JSS 3 (BECE)',
    passportPhoto: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    submittedAt: '2026-03-04T14:30:00Z',
    status: 'Under Review',
    examDate: '2026-03-28',
  },
  {
    id: 'app-003',
    applicationNumber: 'SCH/2026/0003',
    studentFullName: 'David Oluwaseun Adeleke',
    dateOfBirth: '2015-11-08',
    gender: 'Male',
    classApplyingFor: 'Primary 4',
    religion: 'Christianity',
    stateOfOrigin: 'Osun State',
    lga: 'Ede North',
    parentFullName: 'Engr. Tunde Adeleke',
    parentPhone: '08098765432',
    parentEmail: 'tunde.adeleke@outlook.com',
    parentOccupation: 'Software Architect',
    residentialAddress: '24 Chevron Drive, Lekki, Lagos',
    previousSchool: 'Little Angels Nursery & Primary',
    lastClassPassed: 'Primary 3',
    passportPhoto: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=300&auto=format&fit=crop&q=80',
    submittedAt: '2026-03-07T09:45:00Z',
    status: 'Pending',
    examDate: '2026-04-04',
  },
];

export const DEFAULT_RESULTS: StudentResult[] = [
  {
    id: 'res-001',
    regNumber: 'REG/2026/101',
    studentName: 'Somtochukwu Precious Eze',
    classLevel: 'JSS 2 Gold',
    term: '2nd Term',
    session: '2025/2026',
    gender: 'Female',
    passportPhoto: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=300&auto=format&fit=crop&q=80',
    subjects: [
      { id: '1', subjectName: 'Mathematics', ca1: 18, ca2: 19, exam: 55, total: 92, grade: 'A1', remark: 'Distinction' },
      { id: '2', subjectName: 'English Language', ca1: 17, ca2: 18, exam: 52, total: 87, grade: 'A1', remark: 'Distinction' },
      { id: '3', subjectName: 'Basic Science & Tech', ca1: 19, ca2: 17, exam: 54, total: 90, grade: 'A1', remark: 'Distinction' },
      { id: '4', subjectName: 'Computer Studies / ICT', ca1: 20, ca2: 20, exam: 56, total: 96, grade: 'A1', remark: 'Distinction' },
      { id: '5', subjectName: 'Civic Education', ca1: 16, ca2: 17, exam: 49, total: 82, grade: 'B2', remark: 'Very Good' },
      { id: '6', subjectName: 'Agricultural Science', ca1: 18, ca2: 16, exam: 51, total: 85, grade: 'A1', remark: 'Distinction' },
      { id: '7', subjectName: 'Social Studies', ca1: 15, ca2: 18, exam: 48, total: 81, grade: 'B2', remark: 'Very Good' },
      { id: '8', subjectName: 'French Language', ca1: 16, ca2: 15, exam: 47, total: 78, grade: 'B3', remark: 'Good' },
      { id: '9', subjectName: 'Business Studies', ca1: 18, ca2: 19, exam: 53, total: 90, grade: 'A1', remark: 'Distinction' },
    ],
    totalScore: 781,
    maxPossibleScore: 900,
    averageScore: 86.8,
    grade: 'A',
    position: '1st out of 42',
    pin: 'PIN-8492-7104',
    principalRemark: 'An extraordinary performance. Somtochukwu displays brilliant intellect, impeccable discipline, and immense dedication.',
    teacherRemark: 'Consistently attentive, enthusiastic in class discussions, and highly supportive of peers. Keep up the high standard!',
    timesSchoolOpened: 65,
    timesPresent: 65,
    nextTermResumptionDate: '27th April, 2026',
    publishedAt: '2026-03-01T12:00:00Z',
  },
  {
    id: 'res-002',
    regNumber: 'REG/2026/102',
    studentName: 'Toluwalase Daniel Fashola',
    classLevel: 'SSS 2 Science',
    term: '2nd Term',
    session: '2025/2026',
    gender: 'Male',
    passportPhoto: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=300&auto=format&fit=crop&q=80',
    subjects: [
      { id: '1', subjectName: 'Mathematics', ca1: 17, ca2: 16, exam: 50, total: 83, grade: 'B2', remark: 'Very Good' },
      { id: '2', subjectName: 'English Language', ca1: 16, ca2: 17, exam: 46, total: 79, grade: 'B3', remark: 'Good' },
      { id: '3', subjectName: 'Physics', ca1: 18, ca2: 18, exam: 52, total: 88, grade: 'A1', remark: 'Distinction' },
      { id: '4', subjectName: 'Chemistry', ca1: 17, ca2: 18, exam: 51, total: 86, grade: 'A1', remark: 'Distinction' },
      { id: '5', subjectName: 'Biology', ca1: 16, ca2: 15, exam: 48, total: 79, grade: 'B3', remark: 'Good' },
      { id: '6', subjectName: 'Further Mathematics', ca1: 15, ca2: 17, exam: 47, total: 79, grade: 'B3', remark: 'Good' },
      { id: '7', subjectName: 'Civic Education', ca1: 15, ca2: 16, exam: 45, total: 76, grade: 'B3', remark: 'Good' },
      { id: '8', subjectName: 'Data Processing', ca1: 19, ca2: 19, exam: 53, total: 91, grade: 'A1', remark: 'Distinction' },
    ],
    totalScore: 661,
    maxPossibleScore: 800,
    averageScore: 82.6,
    grade: 'A',
    position: '3rd out of 38',
    pin: 'PIN-3190-8452',
    principalRemark: 'Toluwalase shows tremendous promise in pure and applied sciences. Very commendable achievement.',
    teacherRemark: 'Strong analytical abilities and punctual submission of lab work. Highly disciplined.',
    timesSchoolOpened: 65,
    timesPresent: 63,
    nextTermResumptionDate: '27th April, 2026',
    publishedAt: '2026-03-01T12:00:00Z',
  },
  {
    id: 'res-003',
    regNumber: 'REG/2026/103',
    studentName: 'Zainab Halima Danjuma',
    classLevel: 'Primary 5 Emerald',
    term: '2nd Term',
    session: '2025/2026',
    gender: 'Female',
    passportPhoto: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    subjects: [
      { id: '1', subjectName: 'Mathematics', ca1: 19, ca2: 18, exam: 54, total: 91, grade: 'A1', remark: 'Distinction' },
      { id: '2', subjectName: 'English Grammar & Phonics', ca1: 18, ca2: 19, exam: 56, total: 93, grade: 'A1', remark: 'Distinction' },
      { id: '3', subjectName: 'Basic Science', ca1: 18, ca2: 17, exam: 52, total: 87, grade: 'A1', remark: 'Distinction' },
      { id: '4', subjectName: 'Quantitative Reasoning', ca1: 19, ca2: 20, exam: 55, total: 94, grade: 'A1', remark: 'Distinction' },
      { id: '5', subjectName: 'Verbal Reasoning', ca1: 17, ca2: 18, exam: 51, total: 86, grade: 'A1', remark: 'Distinction' },
      { id: '6', subjectName: 'Computer / Coding Basics', ca1: 19, ca2: 18, exam: 53, total: 90, grade: 'A1', remark: 'Distinction' },
      { id: '7', subjectName: 'Social Studies & History', ca1: 16, ca2: 17, exam: 48, total: 81, grade: 'B2', remark: 'Very Good' },
    ],
    totalScore: 622,
    maxPossibleScore: 700,
    averageScore: 88.9,
    grade: 'A',
    position: '2nd out of 30',
    pin: 'PIN-9921-4501',
    principalRemark: 'A delightful and brilliant pupil. Zainab demonstrates remarkable comprehension and leadership among her peers.',
    teacherRemark: 'Active participant in reading circle and science club. Exemplary neatness and handwriting.',
    timesSchoolOpened: 65,
    timesPresent: 64,
    nextTermResumptionDate: '27th April, 2026',
    publishedAt: '2026-03-01T12:00:00Z',
  },
];

export const DEFAULT_GALLERY: GalleryPhoto[] = [
  {
    id: 'gal-1',
    title: 'Ultra-Modern STEM Robotics & AI Innovation Lab',
    category: 'Laboratory',
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
    description: 'Students engaged in interactive coding, electronics, and robotics projects.',
    dateAdded: '2026-02-10',
  },
  {
    id: 'gal-2',
    title: 'Central Library & Research Media Centre',
    category: 'Campus',
    imageUrl: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=800&auto=format&fit=crop&q=80',
    description: 'A serene sanctuary housing over 15,000 physical volumes and digital scholarly archives.',
    dateAdded: '2026-01-15',
  },
  {
    id: 'gal-3',
    title: 'Senior Chemistry & Molecular Research Lab',
    category: 'Laboratory',
    imageUrl: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800&auto=format&fit=crop&q=80',
    description: 'Hands-on practical experiments under certified science educators.',
    dateAdded: '2026-02-04',
  },
  {
    id: 'gal-4',
    title: 'Annual Inter-House Athletics & Sports Championship',
    category: 'Sports',
    imageUrl: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800&auto=format&fit=crop&q=80',
    description: 'Promoting teamwork, sportsmanship, and physical fitness across all houses.',
    dateAdded: '2026-02-20',
  },
  {
    id: 'gal-5',
    title: 'Interactive Smart Board Classrooms',
    category: 'Academics',
    imageUrl: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&auto=format&fit=crop&q=80',
    description: 'Air-conditioned, digitally enabled learning spaces designed for active engagement.',
    dateAdded: '2026-01-28',
  },
  {
    id: 'gal-6',
    title: 'Cultural Heritage & Diversity Fiesta',
    category: 'Events',
    imageUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&auto=format&fit=crop&q=80',
    description: 'Celebrating the rich cultural tapestry of Nigeria and Africa through dance, music, and cuisine.',
    dateAdded: '2025-11-12',
  },
  {
    id: 'gal-7',
    title: 'Fine Arts Studio & Sculpting Workshop',
    category: 'Academics',
    imageUrl: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800&auto=format&fit=crop&q=80',
    description: 'Unleashing creative ingenuity and aesthetic expression in our budding artists.',
    dateAdded: '2026-01-05',
  },
  {
    id: 'gal-8',
    title: 'Graduation & Speech Day Ceremony',
    category: 'Events',
    imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&auto=format&fit=crop&q=80',
    description: 'Honoring outstanding scholastic and leadership accomplishments.',
    dateAdded: '2025-07-22',
  },
];

export const DEFAULT_NEWS: NewsItem[] = [
  {
    id: 'news-1',
    title: 'Apex Royal Students Win Gold at National STEM Olympiad 2026',
    excerpt:
      'Our senior science delegation bagged 3 gold medals and 2 silver medals at the Federal Mathematical Sciences & Robotics Championship.',
    content:
      'We are thrilled to announce that our senior secondary robotics and mathematics team emerged overall best among 180 participating schools nationwide at the National STEM Olympiad held in Abuja. The team presented an automated solar irrigation model and scored maximum points in the mental mathematics challenge. Hearty congratulations to our brilliant champions and their dedicated coaches!',
    category: 'News',
    imageUrl: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?w=800&auto=format&fit=crop&q=80',
    publishDate: '2026-03-05',
    author: 'Head of Science Department',
  },
  {
    id: 'news-2',
    title: '2026/2027 Entrance Examination & Scholarship Screening Date Announced',
    excerpt:
      'The first batch of entrance examinations for prospective JSS1 and SSS1 scholars is slated for Saturday, 28th March 2026.',
    content:
      'Parents and guardians seeking admission for their wards into Nursery, Primary, JSS 1-3, and SSS 1-2 for the 2026/2027 academic session are hereby notified that the initial entrance screening holds on Saturday, 28th March 2026 by 9:00 AM prompt at the Main Campus Auditorium. Merit-based tuition scholarships will be awarded to the top 5 candidates. Online application is accessible via our Admissions Portal.',
    category: 'Announcement',
    imageUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&auto=format&fit=crop&q=80',
    publishDate: '2026-02-25',
    author: 'Registrar & Admissions Office',
  },
  {
    id: 'news-3',
    title: 'Annual Inter-House Sports Gala & Family Fun Carnival',
    excerpt:
      'Join us for an electrifying showcase of athletic prowess, track & field events, and family festivities on 18th April 2026.',
    content:
      'The management cordially invites all parents, alumni, and friends of the academy to our 16th Biennial Inter-House Sports Festival holding at the Campus Sports Pavilion on Saturday, 18th April 2026. Red, Blue, Yellow, and Green houses will contest for the prestigious Golden Jubilee Trophy across 24 track and field disciplines.',
    category: 'Event',
    imageUrl: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800&auto=format&fit=crop&q=80',
    publishDate: '2026-02-18',
    eventDate: '2026-04-18',
    author: 'Director of Physical Education',
  },
];

export const DEFAULT_PINS: ResultPin[] = [
  {
    id: 'pin-1',
    pin: 'PIN-8492-7104',
    serialNumber: 'SN-2026-001',
    status: 'used',
    assignedToRegNo: 'REG/2026/101',
    studentName: 'Somtochukwu Precious Eze',
    timesUsed: 1,
    maxUsage: 5,
    createdAt: '2026-02-28',
  },
  {
    id: 'pin-2',
    pin: 'PIN-3190-8452',
    serialNumber: 'SN-2026-002',
    status: 'used',
    assignedToRegNo: 'REG/2026/102',
    studentName: 'Toluwalase Daniel Fashola',
    timesUsed: 1,
    maxUsage: 5,
    createdAt: '2026-02-28',
  },
  {
    id: 'pin-3',
    pin: 'PIN-9921-4501',
    serialNumber: 'SN-2026-003',
    status: 'used',
    assignedToRegNo: 'REG/2026/103',
    studentName: 'Zainab Halima Danjuma',
    timesUsed: 1,
    maxUsage: 5,
    createdAt: '2026-02-28',
  },
  {
    id: 'pin-4',
    pin: 'PIN-5820-1194',
    serialNumber: 'SN-2026-004',
    status: 'unused',
    timesUsed: 0,
    maxUsage: 5,
    createdAt: '2026-03-01',
  },
  {
    id: 'pin-5',
    pin: 'PIN-7341-9928',
    serialNumber: 'SN-2026-005',
    status: 'unused',
    timesUsed: 0,
    maxUsage: 5,
    createdAt: '2026-03-01',
  },
  {
    id: 'pin-6',
    pin: 'PIN-1049-8832',
    serialNumber: 'SN-2026-006',
    status: 'unused',
    timesUsed: 0,
    maxUsage: 5,
    createdAt: '2026-03-01',
  },
  {
    id: 'pin-7',
    pin: 'PIN-6402-3155',
    serialNumber: 'SN-2026-007',
    status: 'unused',
    timesUsed: 0,
    maxUsage: 5,
    createdAt: '2026-03-01',
  },
  {
    id: 'pin-8',
    pin: 'PIN-4281-7093',
    serialNumber: 'SN-2026-008',
    status: 'unused',
    timesUsed: 0,
    maxUsage: 5,
    createdAt: '2026-03-01',
  },
];

export const DEFAULT_TEACHERS: Teacher[] = [
  {
    id: 't-1',
    name: 'Mrs. Victoria Ade-Johnson, M.Ed',
    role: 'Principal & Head of School',
    qualification: 'B.Sc. Ed (Ibadan), M.Ed Educational Leadership (Nottingham)',
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
    bio: 'Over 22 years of transformative leadership in international educational administration.',
  },
  {
    id: 't-2',
    name: 'Mr. Jude Chukwuma, M.Sc',
    role: 'Vice Principal (Academics)',
    qualification: 'B.Sc Mathematics (UNN), M.Sc Applied Statistics (Lagos)',
    image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&auto=format&fit=crop&q=80',
    bio: 'Passionate STEM pioneer with specialized focus on curriculum integration and olympiad prep.',
  },
  {
    id: 't-3',
    name: 'Dr. (Mrs.) Folashade Bakare',
    role: 'Head of Sciences',
    qualification: 'Ph.D Biochemistry (Ife), Member Chemical Society of Nigeria',
    image: 'https://images.unsplash.com/photo-1580894732444-8ecded7900cd?w=400&auto=format&fit=crop&q=80',
    bio: 'Mentoring young scientists with hands-on laboratory research and scientific inquiry.',
  },
  {
    id: 't-4',
    name: 'Mr. Raymond Mensah',
    role: 'Head of Humanities & Arts',
    qualification: 'B.A. English & Literary Studies (Legon), PGDE',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    bio: 'Championing creative writing, public speaking, and dramatic arts excellence.',
  },
];
